### ISSUE TITLE
Question | Receiving OSC

### ISSUE THREAD

**Issue by pickleshb** [Figure53/F53OSC#16]
Can this library receive OSC as I can't see any methods, but I may just be being dense

**Comment by ChrisAshworth** [comment]
Yup! The included demo shows an example of setting up an OSC server to receive OSC:

https://github.com/Figure53/F53OSC/blob/master/F53OSC%20Monitor/F53OSC%20Monitor/DemoServer.m

**Comment by pickleshb** [comment]
Awesome
