### ISSUE TITLE
Cannot install from CocoaPods

### ISSUE THREAD

**Issue by 0x0c** [Figure53/F53OSC#21]
I cannot install F53OSC from CocoaPods and cannot find this library in https://cocoapods.org.

The error is below in the terminal.

```
[!] Unable to find a specification for `F53OSC`

You have either:
 * out-of-date source repos which you can update with `pod repo update` or with `pod install --repo-update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.

Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by balord** [comment]
Hi there --

We don't have the F53OSC podspec listed in cocopods.org yet, which I suspect is the reason for your error.

Instead, include this line in your Podfile which will tell CocoaPods to install F53OSC directly from the GitHub repo:

```
pod 'F53OSC', :git => 'https://github.com/Figure53/F53OSC.git'
```

**Comment by 0x0c** [comment]
Thank you!
