### ISSUE TITLE
Use SLIP protocol for TCP connections

### ISSUE THREAD

**Issue by ChrisAshworth** [Figure53/F53OSC#3]
The OSC 1.0 spec recommend using a size-count-preamble to send OSC messages over TCP. F53OSC currently uses this method.

However, the OSC 1.1 protocol changed this recommendation, and now OSC over TCP is required to employ SLIP (RFC1055) with a double END character encoding:

http://cnmat.berkeley.edu/publication/features_and_future_open_sound_control_version_1_1_nime

Need to change F53OSC to use SLIP for TCP connections:

http://www.rfc-editor.org/rfc/rfc1055.txt

**Comment by richardwilliamson** [comment]
I know this is closed but just as a thought, the default setting on Eos for OSC is version 1.0 - which means that the settings have to be changed to communicate over TCP with an eos console, it would be useful if there was an option on the OSCClient to use OSC version 1.0 packets..

**Comment by ChrisAshworth** [comment]
Hi Richard,

Hm, my recollection is version 1.0 provided no guidance for how to use a TCP connection at all, so "using 1.0" roughly means either not using TCP or inventing some custom framing mechanism for it. 

(mobile)

**Comment by richardwilliamson** [comment]
I’ve only really done TCP OSC stuff previously with an arduino library talking to eos - that worked happily with just a normal non-SLIP encoded message, it just transmitted the messages in the same way it did with UDP but over TCP. My knowledge of network protocols is only just above zero though so I don’t fully know what I’m talking about - the arduino code I used to listen to recieved TCP OSC was:

 MsgLength len;  //a struct for the length
    len.value = 0; //preset it to 0

    byte f4 = 4; //first 4 bytes are the size, then we have the actual message..
    //get the size
    while (f4--)
    {
      len.bytes[f4] = client.read();
      rdS--;
    }

    String str = "";
    OSCMessage(rMsg);

    while (len.value--)
      //str +=(char)client.read();
      rMsg.fill(client.read());

    // Serial.println(wheelC);


    if (!rMsg.hasError() && (rMsg.match("/eos/out/active", 0) > 12 || rMsg.match("/eos/out/cmd", 0) > 10)  )
	//do something with the OSC message
--
Richard Williamson
www.richard-williamson.com
richard@richard-williamson.com
07957 457 362

**Comment by SammyTheHand** [comment]
I'm not sure what arduino library you are using but there is one made by the creators of OSC Tom Wright & Adrian Freed that certainly includes and promotes the use of the end slip protocol which is included in the OSC 1.1 spec.

https://github.com/CNMAT/OSC/blob/master/README.md

Having been the person to suggest the option to change the protocol version in the Eos shell I can certainly understand your problems with aspects of the two versions.
 
The implementation of the SLIP protocol was written in the spec in 2009 so I have no idea why people are still using OSC 1.0 I presume it's easier to implement..

I would suggest using OSC Router an application written by Electronic Theatre Controls to convert from version to version.

Having been

**Comment by ChrisAshworth** [comment]
LOL — serves me right to send a reply from my email client without re-reading the ticket. If I'd done so I would have seen that not only did 1.0 provide guidance, but apparently we used a different method at one point. Quoting myself:

> The OSC 1.0 spec recommend using a size-count-preamble to send OSC messages over TCP. F53OSC currently uses this method.

Sorry @richardwilliamson for being too quick on the reply button there! How do folks feel about me creating a new issue to track this separately?

**Comment by richardwilliamson** [comment]
That sounds sensible to me! Thanks!!
