### ISSUE TITLE
Archive URL

### ISSUE THREAD

**Issue by fchen09** [Figure53/F53OSC#40]
Hi,
I am trying to import your lib with the tool: https://github.com/pinterest/PodToBUILD
What is the correct url for F53OSC?
I have tried https://github.com/Figure53/F53OSC.git, but it did not work.
Thank you!

**Comment by balord** [comment]
Hi there -- 

I'm not familiar with PodToBUILD personally but from the README, could you try using the URL of a downloadable archive instead?

Check out the **Tags** page here: https://github.com/Figure53/F53OSC/tags and see if one of the links to a .zip perhaps works.
