### ISSUE TITLE
Problem updating from v1.2.0 to v1.3.0

### ISSUE THREAD

**Issue by latenitefilms** [Figure53/F53OSC#46]
I just attempted to try updating from v1.2.0 to v1.3.0 and I'm getting the following error:

```
[F53OSC] Compiling F53OSCSocket.m
❌ /Users/chrishocking/Documents/GitHub/CommandPost-App/Pods/F53OSC/Sources/F53OSC/F53OSCSocket.m:316:30: receiver type 'F53OSCEncrypt' for instance message is a forward declaration
        NSData *encrypted = [self.encrypter encryptDataWithClearData:data];
                             ^~~~~~~~~~~~~~
❌ /Users/chrishocking/Documents/GitHub/CommandPost-App/Pods/F53OSC/Sources/F53OSC/F53OSCSocket.m:392:24: receiver 'F53OSCEncrypt' for class message is a forward declaration
    self.encrypter = [[F53OSCEncrypt alloc] initWithKeyPairData:keyPair];
                       ^~~~~~~~~~~~~
❌ /Users/chrishocking/Documents/GitHub/CommandPost-App/Pods/F53OSC/Sources/F53OSC/F53OSCSocket.m:392:23: receiver type 'F53OSCEncrypt' for instance message is a forward declaration
    self.encrypter = [[F53OSCEncrypt alloc] initWithKeyPairData:keyPair];
                      ^~~~~~~~~~~~~~~~~~~~~
```

Any ideas?

**Comment by balord** [comment]
`F53OSCEncrypt` is written in Swift, so you may need to adjust your project settings slightly to bridge the Swift with your Objective-C code if this is the first time you are incorporating Swift code in it.

Does your `Podfile` specify `use_frameworks!` anywhere in it? This tells CocoaPods to build your pods as frameworks, which might be all you need to do, as the `F53OSC.h` header includes the necessary generated Swift header file when built as a framework.

If you aren't able to do that in your Podfile, you can try adding an `#import` to your app's generated Objective-C interface in your app .pch file. The exact name can be found in your Build settings under "Swift Compiler - General" -> "Objective-C Generated Interface Header Name". It will be something like "My_App-Swift.h".
